apiVersion: v1
kind: Pod
metadata:
  name: curl-uninjected
  labels:
    app: curl-uninjected
spec:
  containers:
    - name: curl
      image: docker.io/curlimages/curl:latest
      command: ["/bin/sh", "-c"]
      args: ["while true; do :; done"]